services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: support-ticket-back
        ports:
            - '${APP_PORT:-8080}:80'
            - '2200:22'  # Puerto para SSH
            - '${VITE_PORT:-5173}:5173'
        volumes:
            - '.:/var/www/html:delegated'  # Montar código para desarrollo
            - '~/.ssh:/home/developer/.ssh:ro'  # Montar claves SSH del host
        networks:
            - sail
        depends_on:
            - mysql
            - redis
        restart: unless-stopped
        environment:
            DB_HOST: mysql
            REDIS_HOST: redis
            APACHE_DOCUMENT_ROOT: /var/www/html/public
            PHP_DISPLAY_ERRORS: 1

    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3307}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s

    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6380}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s

networks:
    sail:
        driver: bridge

volumes:
    sail-mysql:
        driver: local
    sail-redis:
        driver: local
